// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharp_api_demo_bands.Models;

#nullable disable

namespace csharp_api_demo_bands.Migrations
{
    [DbContext(typeof(BandsContext))]
    [Migration("20240919134809_InitBandsDB")]
    partial class InitBandsDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("csharp_api_demo_bands.Models.Band", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StyleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StyleID");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("csharp_api_demo_bands.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Styles");
                });

            modelBuilder.Entity("csharp_api_demo_bands.Models.Band", b =>
                {
                    b.HasOne("csharp_api_demo_bands.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });
#pragma warning restore 612, 618
        }
    }
}
